name: 应用发布流程

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: 检出项目
      uses: actions/checkout@v1

    - name: 使用JDK 1.8 环境
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: 编译release包
      env:
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        chmod +x ./gradlew
        ./gradlew asRe

    - name: 上传产出物
      uses: actions/upload-artifact@v1
      with:
        name: release-artifact
        path: app/build/outputs

    - name: 创建 GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 上传发布资源
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/com.jacknic.circleci-release.apk
        asset_name: com.jacknic.circleci-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: 上传发布资源2
      id: upload-release-asset2 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/com.jacknic.circleci-release.apk
        asset_name: com.jacknic.circleci-release2.apk
        asset_content_type: application/vnd.android.package-archive